name: sekolahku
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  faker: ^1.3.0
  sqflite:
  flutter_native_splash:
  flutter_launcher_icons: ^0.9.0
  simple_speed_dial: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/images/sekolah.png
  color: "#78c0f0"

flutter_icons:
  image_path: "assets/images/sekolah.png"
  android: "launcher_icon"
  ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/pria.png
    - assets/images/wanita.png
    - assets/images/sekolah.png
